dependencyArtifactsName=cimeliarchium-artifacts
dependencyArtifactsVersion=0.0.1

dependencyApacheCommonsLang3Version=3.14.0
#03/21, latest as of 01/24
dependencyApacheTomcatEmbedJasperVersion=9.0.62
#04/22, latest as of 01/24
dependencyCommonsBeanutilsVersion=1.9.4
#08/19, latest as of 01/24
dependencyCommonsIOVersion=2.11.0
#07/22, latest as of 01/24
dependencyGuavaVersion=33.0.0-jre
#12/23, latest as of 01/24
dependencyGsonVersion=2.10.1
#01/23, latest as of 01/24
dependencyHibernateValidatorVersion=8.0.1.Final
#06/23, latest as of 01/24
dependencyHttpClientVersion=4.5.14
#11/22, latest as of 01/24
dependencyJavaxActivation=1.1.1
#10/09, latest as of 01/24
dependencyJavaxPersistenceApiVersion=2.2
#08/17, latest as of 01/24
dependencyJavaxValidationApiVersion=2.0.1.Final
#12/17, latest as of 01/24
dependencyJaxbVersion=2.3.1
#10/18, latest as of 01/24
dependencyJaxbImplVersion=4.0.4
#10/23, latest as of 01/24
dependencyJodaTimeVersion=2.12.5
#03/23, latest as of 01/24
dependencyJstlVersion=1.2
#05/15, latest as of 01/24
dependencyJunitVersion=4.13.2
#02/21, latest as of 01/24
dependencyJupiterApiVersion=5.10.1
#11/23, latest as of 01/24
dependencyMockitoVersion=5.8.0
#12/23, latest as of 01/24
dependencyPaypalVersion=1.0.5
#09/21, latest as of 01/24
dependencyPdfboxVersion=2.0.30
#11/23, latest as of 01/24
dependencyPoiVersion=5.2.5
#11/23, latest as of 01/24
dependencyPostgresqlVersion=42.7.1
#12/23, latest as of 01/24
dependencyPowermockVersion=2.0.9
#11/20, latest as of 01/24
dependencyJavaxServletApiVersion=4.0.1
#02/18, latest as of 01/24
dependencySlf4jVersion=1.7.36
#02/22, skipped update to SLF4J2 as of 01/24
dependencySpringBootVersion=2.6.7
#02/22, skipped update to SLF4J2 as of 01/24
dependencySpringSecurityVersion=5.6.9
#04/22, skipped update to SLF4J2 as of 01/24
dependencySpringTestVersion=5.3.27
#04/22, skipped update to SLF4J2 as of 01/24
dependencyWebjarsBootstrapVersion=4.3.1
#10/21, skipped update as of 01/24
dependencyWebjarsDatatablesVersion=1.13.5
#07/23, latest as of 01/24
dependencyWebjarsJqueryUIVersion=1.13.1
#08/22, skipped update as of 01/24
dependencyWebjarsJqueryVersion=3.6.0
#03/21, skipped update as of 01/24
dependencyWebjarsLeafletVersion=1.8.0
#07/22, latest as of 01/24
dependencyWebjarsLocatorCoreVersion=0.55
#11/23, latest as of 01/24
